---
galaxy_info:
  author: Manjaro Ansible Config
  description: Common system configuration for Manjaro Linux
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - system
    - common
    - base

dependencies: []