---
galaxy_info:
  author: Manjaro Ansible Config
  description: Dotfile management with chezmoi integration
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - system
    - dotfiles
    - chezmoi
    - configuration

dependencies: []