---
galaxy_info:
  author: Manjaro Ansible Config
  description: Development tools and environment setup
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - development
    - tools
    - programming

dependencies: []