---
- name: Converge
  hosts: all
  tasks:
    - name: Install systemd
      package:
        name: systemd
        state: present
      become: yes

    - name: Start systemd
      command: systemctl --version
      changed_when: false

- import_playbook: ../../playbooks/site.yml