---
dependency:
  name: galaxy
  options:
    requirements-file: ../../collections/requirements.yml

driver:
  name: docker

platforms:
  - name: manjaro-test
    image: manjarolinux/base
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/usr/lib/systemd/systemd"
    published_ports:
      - "2222:22/tcp"

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ../../roles
      collections_path: ../../collections
  playbooks:
    converge: ../../playbooks/site.yml
  inventory:
    group_vars:
      all:
        aur_builder_user: test_builder

verifier:
  name: testinfra
  directory: ../../tests/