---
galaxy_info:
  author: Manjaro Ansible Config
  description: Package management for Manjaro Linux
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - system
    - packages
    - manjaro
    - arch

dependencies: []